import { AuthContext } from "./AuthContext";

const navSup = [
  {
    id: 1,
    title: "Home",
    to: "/",
  },
];
const navMid = [
  {
    id: 2,
    title: "C.R.E.A.M",
    to: "cream",
  },
  {
    id: 3,
    title: "TIGER",
    to: "tiger",
  },
  {
    id: 4,
    title: "BEER & CHURROS",
    to: "beer&churros",
  },
  {
    id: 5,
    title: "OGs",
    to: "ogs",
  },
  {
    id: 6,
    title: "ACCESORIOS",
    to: "accesorios",
  },
];
const navMid2 = [
  {
    id: 7,
    title: "Carrito",
    to: "shop",
  },
  {
    id: 8,
    title: "Login",
    to: "contact",
  },
  {
    id: 9,
    title: "Registrarse",
    to: "registro",
  },
];
const mainConjuntos = [
  {
    id: 1,
    title: "TIGER",
    src: "/public/assets/conjunto1.jpg",
    to: "tiger",
  },
  {
    id: 2,
    title: "C.R.E.A.M.",
    src: "/public/assets/conjunto2.jpg",
    to: "cream",
  },
];
const mainConjuntos2 = [
  {
    id: 3,
    title: "BEER & CHURROS",
    src: "/public/assets/conjunto3.jpg",
    to: "beer&churros",
  },
  {
    id: 4,
    title: "OG'S",
    src: "/public/assets/conjunto4.jpg",
    to: "ogs",
  },
  {
    id: 5,
    title: "ACCESORIOS",
    src: "/public/assets/conjunto5.jpg",
    to: "accesorios",
  },
];
const footerLeft = [
  {
    id: 1,
    title: "@2023 Reserva todos los derechos",
  },
];
const footerRight = [
  {
    id: 2,
    title: "Política de envíos",
    href: "https://www.ogsbrand.com/es/politica-de-envios/",
  },
  {
    id: 3,
    title: "Contacto",
    href: "https://www.ogsbrand.com/es/contacto/",
  },
  {
    id: 4,
    title: "Condiciones de compra",
    href: "https://www.ogsbrand.com/es/condiciones-de-compra/",
  },
  {
    id: 5,
    title: "Términos de servicio",
    href: "https://www.ogsbrand.com/es/terminos-de-servicio/",
  },
  {
    id: 6,
    title: "Política de privacidad",
    href: "https://www.ogsbrand.com/es/politica-de-privacidad/",
  },
  {
    id: 7,
    title: "Política de cookies",
    href: "https://www.ogsbrand.com/es/politica-de-cookies/",
  },
  {
    id: 8,
    title: "Legal",
    href: "https://www.ogsbrand.com/es/legal/",
  },
  {
    id: 9,
    title: "Tallas",
    href: "https://www.ogsbrand.com/es/tallas/",
  },
  {
    id: 10,
    title: "Recomendaciones de cuidado",
    href: "https://www.ogsbrand.com/es/care-recommendations/",
  },
];
const tiger = [
  {
    id: 1,
    src1: "/public/assets/camiseta_tiger.jpg",
    src2: "/public/assets/camiseta_tiger-complementaria3.jpg",
    src3: "/public/assets/camiseta_tiger-complementaria2.jpg",
    src4: "/public/assets/camiseta_tiger-hover.jpg",
    title: "TIGER - Camiseta Relaxed Fit",
    alt: "TIGER - Camiseta Relaxed Fit",
    precio: "32,99€",
    to: "tiger-1",

    text: "Pa los tigres rectos",
    text2: "Marcos mide 177cm y lleva una talla L",
    complementocolor2: "/public/assets/camiseta_tiger-hover.jpg",
    complementocolor1: "/public/assets/camiseta_tiger-complementaria3.jpg",
    element1: "240gsm",
    element2: "100% algodón",
    element3: "Relaxed fit",
    element4: "Guía de tallas y recomendaciones de cuidado",
    comprasimilar1: "/public/assets/sudadera1_cream.jpg",
    altsimilar1: "Sudadera-cream",
    comprasimilar2: "/public/assets/camiseta1_beer.jpg",
    altsimilar2: "Camiseta-beer",
    to1: "ogs",
    to2: "beer&churros",
  },
  {
    id: 2,
    src1: "/public/assets/sudadera1_tiger.jpg",
    src2: "/public/assets/sudadera1_tiger-carrusel.jpg",
    src3: "/public/assets/sudadera1_tiger-hover.jpg",
    src4: "/public/assets/sudadera1_tiger-carrusel2.jpg",
    title: "TIGER - Sudadera con Capucha",
    alt: "TIGER - Sudadera con Capucha",
    precio: "42,99€",
    to: "tiger-2",

    text: "Pa los tigres rectos",
    text2: "",
    complementocolor2: "/public/assets/sudadera1_tiger-hover.jpg",
    complementocolor1: "/public/assets/sudadera1_tiger-carrusel.jpg",
    element1: "280 g/m², 80% algodón, 20% poliéster",
    element2: "Capucha de doble capa con cordón de ajuste.",
    element3: "Bolsillo canguro.",
    element4: "Guía de tallas y recomendaciones de cuidado",
    comprasimilar1: "/public/assets/sudadera1_cream.jpg",
    altsimilar1: "Sudadera-cream",
    comprasimilar2: "/public/assets/camiseta1_beer.jpg",
    altsimilar2: "Camiseta-beer",
    to1: "ogs",
    to2: "beer&churros",
  },
  {
    id: 3,
    src1: "/public/assets/sudadera2_tiger-hover.jpg",
    src2: "/public/assets/sudadera2_tiger-carrusel2.jpg",
    src3: "/public/assets/sudadera2_tiger-carrusel1.jpg",
    src4: "/public/assets/sudadera2_tiger.jpg",
    title: "TIGER - Sudadera",
    alt: "TIGER - Sudadera",
    precio: "39,99€",
    to: "tiger-3",

    text: "Pa los tigres rectos",
    text2: "",
    complementocolor2: "/public/assets/sudadera2_tiger.jpg",
    complementocolor1: "/public/assets/sudadera2_tiger-carrusel2.jpg",
    element1: "280 g/m², 80% algodón ring-spun y peinado, 20% poliéster",
    element2: "Tejido de 3 capas",
    element3: "Sisas, puños y bajo con tapa costura",
    element4: "Guía de tallas y recomendaciones de cuidado",
    comprasimilar1: "/public/assets/sudadera1_cream.jpg",
    altsimilar1: "Sudadera-cream",
    comprasimilar2: "/public/assets/camiseta1_beer.jpg",
    altsimilar2: "Camiseta-beer",
    to1: "ogs",
    to2: "beer&churros",
  },
];
const cream = [
  {
    id: 1,
    src2: "/public/assets/sudadera2_cream.jpg",
    src1: "/public/assets/sudadera2_cream-hover.jpg",
    src4: "/public/assets/sudadera1_cream.jpg",
    src3: "/public/assets/sudadera1_cream-hover.jpg",
    title: "C.R.E.A.M. - Sudadera Beige",
    alt: "C.R.E.A.M. - Sudadera Beige",
    precio: "59,99€",
    to: "cream-1",

    text: "Un relanzamiento de la prenda estrella del año pasado. Nuevo color, nuevos bordados, misma esencia.",
    text2: "",
    complementocolor1: "/public/assets/sudadera2_cream.jpg",
    complementocolor2: "/public/assets/sudadera1_cream.jpg",
    element1: "65% Algodón / 35% Poliéster",
    element2: "Bolsillo delantero con cierre de cremallera",
    element3: "Logos bordados con hilo metálico",
    element4: "Guía de tallas y recomendaciones de cuidado",
    comprasimilar1: "/public/assets/sudadera2_tiger-carrusel1.jpg",
    altsimilar1: "Sudadera-cream",
    comprasimilar2: "/public/assets/gorra1_ogs.jpg",
    altsimilar2: "Camiseta-beer",
    to1: "tiger",
    to2: "accesorios",
  },
  {
    id: 2,
    src4: "/public/assets/sudadera2_cream.jpg",
    src3: "/public/assets/sudadera2_cream-hover.jpg",
    src2: "/public/assets/sudadera1_cream.jpg",
    src1: "/public/assets/sudadera1_cream-hover.jpg",
    title: "C.R.E.A.M. - Sudadera Negra",
    alt: "C.R.E.A.M. - Sudadera Negra",
    precio: "59,99€",
    to: "cream-2",

    text: "Un relanzamiento de la prenda estrella del año pasado. Nuevo color, nuevos bordados, misma esencia.",
    text2: "",
    complementocolor1: "/public/assets/sudadera1_cream.jpg",
    complementocolor2: "/public/assets/sudadera2_cream.jpg",
    element1: "65% Algodón / 35% Poliéster",
    element2: "Bolsillo delantero con cierre de cremallera",
    element3: "Logos bordados con hilo metálico",
    element4: "Guía de tallas y recomendaciones de cuidado",
    comprasimilar1: "/public/assets/sudadera2_tiger-carrusel1.jpg",
    altsimilar1: "Sudadera-cream",
    comprasimilar2: "/public/assets/gorra1_ogs.jpg",
    altsimilar2: "Camiseta-beer",
    to1: "tiger",
    to2: "accesorios",
  },
];
const beerAndChurros = [
  {
    id: 1,
    src1: "/public/assets/camiseta1_beer.jpg",
    src2: "/public/assets/camiseta1_beer-hover.jpg",
    title: "KOREAN BEER - Camiseta",
    alt: "KOREAN BEER - Camiseta",
    precio: "26.99 €",
    to: "beer-1",
  },
  {
    id: 2,
    src1: "/public/assets/sudadera1_beer.jpg",
    src2: "/public/assets/sudadera1_beer-hover.jpg",
    title: "KOREAN BEER - Sudadera con Capucha",
    alt: "KOREAN BEER - Sudadera con Capucha",
    precio: "42.99 €",
    to: "beer-2",
  },
  {
    id: 3,
    src1: "/public/assets/sudadera2_beer.jpg",
    src2: "/public/assets/sudadera2_beer-hover.jpg",
    title: "KOREAN BEER - Sudadera",
    alt: "KOREAN BEER - Sudadera",
    precio: "39,99€",
    to: "beer-3",
  },
  {
    id: 4,
    src1: "/public/assets/camiseta2_beer.jpg",
    src2: "/public/assets/camiseta2_beer-hover.jpg",
    title: "2 RATS 1 CHURRO - Camiseta",
    alt: "2 RATS 1 CHURRO - Camiseta",
    precio: "26,99€",
    to: "beer-4",
  },
  {
    id: 5,
    src1: "/public/assets/sudadera3_beer.jpg",
    src2: "/public/assets/sudadera3_beer-hover.jpg",
    title: "2 RATS 1 CHURRO - Sudadera con Capucha",
    alt: "2 RATS 1 CHURRO - Sudadera con Capucha",
    precio: "42,99€",
    to: "beer-5",
  },
  {
    id: 6,
    src1: "/public/assets/sudadera4_beer.jpg",
    src2: "/public/assets/sudadera4_beer-hover.jpg",
    title: "2 RATS 1 CHURRO - Sudadera",
    alt: "2 RATS 1 CHURRO - Sudadera",
    precio: "39,99€",
    to: "beer-6",
  },
];
const ogs = [
  {
    id: 1,
    src1: "/public/assets/camiseta1_ogs.jpg",
    src2: "/public/assets/camiseta1_ogs-hover.jpg",
    title: "OG's - Camiseta",
    alt: "OG's - Camiseta",
    precio: "24.99 €",
    to: "ogs-1",
  },
  {
    id: 2,
    src1: "/public/assets/camiseta2_ogs.jpg",
    src2: "/public/assets/camiseta2_ogs-hover.jpg",
    title: "OG's 2.0 - Camiseta",
    alt: "OG's 2.0 - Camiseta",
    precio: "24.99 €",
    to: "ogs-2",
  },
  {
    id: 3,
    src1: "/public/assets/sudadera2_ogs.jpg",
    src2: "/public/assets/sudadera2_ogs-hover.jpg",
    title: "OG's - Sudadera con Capucha",
    alt: "OG's - Sudadera con Capucha",
    precio: "42.99 €",
    to: "ogs-3",
  },
  {
    id: 4,
    src1: "/public/assets/sudadera3_ogs.jpg",
    src2: "/public/assets/sudadera3_ogs-hover.jpg",
    title: "OG's 2.0 - Sudadera Con Capucha",
    alt: "OG's 2.0 - Sudadera Con Capucha",
    precio: "42.99 €",
    to: "ogs-4",
  },
  {
    id: 5,
    src1: "/public/assets/sudadera4_ogs.jpg",
    src2: "/public/assets/sudadera4_ogs-hover.jpg",
    title: "OG's 2.0 Black on Black- Sudadera",
    alt: "OG's 2.0 Black on Black- Sudadera",
    precio: "42.99 €",
    to: "ogs-5",
  },
  {
    id: 6,
    src1: "/public/assets/camiseta3_ogs.jpg",
    src2: "/public/assets/camiseta3_ogs-hover.jpg",
    title: "OG's 2.0 Black on Black - Camiseta",
    alt: "OG's 2.0 Black on Black - Camiseta",
    precio: "24.99 €",
    to: "ogs-6",
  },
];
const accesorios = [
  {
    id: 1,
    src1: "/public/assets/gorra3_ogs.jpg",
    src2: "/public/assets/gorra3_ogs-hover.jpg",
    src3: "/public/assets/gorra3_ogs-complementaria.jpg",
    src4: "/public/assets/gorra3_ogs.jpg",

    title: "OG's - Beanie",
    alt: "OG's - Beanie",
    precio: "19.99 €",
    to: "accesorios-1",

    text: "Gorro con el logo bordado para estos días de intensísimo frío, menos si vives en Málaga, que probablemente hasta mediados de Marzo de 2025 no te hará falta porque el cambio climático es un tema bastante chungo.",
    text2: "",
    complementocolor1: "",
    complementocolor2: "",
    element1: "Punto tricotado.",
    element2: "100% algodón orgánico.",
    element3: "Talla única.",
    element4: "Este artículo NO admite devolución.",
    comprasimilar1: "/public/assets/calcetines_ogs.jpg",
    altsimilar1: "accesorios",
    comprasimilar2: "/public/assets/camiseta_tiger-hover.jpg",
    altsimilar2: "camiseta-tiger",
    to1: "accesorios",
    to2: "tiger",
  },
  {
    id: 2,
    src1: "/public/assets/calcetines_ogs.jpg",
    src2: "/public/assets/calcetines_ogs-hover.jpg",
    src3: "/public/assets/calcetines_ogs-complementaria1.jpg",
    src4: "/public/assets/calcetines_ogs-complementaria2.jpg",
    title: "SOGS",
    alt: "SOGS",
    precio: "24.99 €",
    to: "accesorios-2",

    text: "3 pares de calcetines con estilo simple, clásico y efectivo. Perfectos para combinarlos con tus mejores chanclas como los guiris en Mallorca",
    text2: "",
    complementocolor1: "/public/assets/calcetines_ogs-complementaria1.jpg",
    complementocolor2: "/public/assets/calcetines_ogs-complementaria2.jpg",
    element1: " 76% Algodón",
    element2: "20% Poliéster y 4% Spandex",
    element3: "Talla única.",
    element4: "Este artículo NO admite devolución.",
    comprasimilar1: "/public/assets/calcetines_ogs.jpg",
    altsimilar1: "accesorios",
    comprasimilar2: "/public/assets/camiseta_tiger-hover.jpg",
    altsimilar2: "camiseta-tiger",
    to1: "accesorios",
    to2: "tiger",
  },
  {
    id: 3,
    src1: "/public/assets/gorra1_ogs.jpg",
    src2: "/public/assets/gorra1_ogs-hover.jpg",
    src3: "/public/assets/gorra1_ogs.jpg",
    src4: "/public/assets/gorra1_ogs-hover.jpg",
    title: "KIR - Gorra",
    alt: "KIR - Gorra",
    precio: "29.99 €",
    to: "ogs-3",

    text: "Logo y frase bordadas, simple y efectiva. Pa tapar el flequillo asintomático",
    text2: "",
    comprasimilar1: "/public/assets/calcetines_ogs.jpg",
    altsimilar1: "accesorios",
    comprasimilar2: "/public/assets/camiseta_tiger-hover.jpg",
    altsimilar2: "camiseta-tiger",
    to1: "accesorios",
    to2: "tiger",
    text: "Logo y frase bordadas, simple y efectiva. Pa tapar el flequillo asintomático",
    text2: "",
    complementocolor1: "",
    complementocolor2: "",
    element1: "100% poliéster reciclado",
    element2: "Ala ancha y redondeada",
    element3: "6 paneles",
    element4: "Este artículo NO admite devolución",
  },
];
export const Provider = ({ children }) => {
  return (
    <AuthContext.Provider
      value={{
        navSup,
        navMid,
        navMid2,
        mainConjuntos,
        mainConjuntos2,
        footerLeft,
        footerRight,
        tiger,
        cream,
        beerAndChurros,
        ogs,
        accesorios,
      }}
    >
      {children}
    </AuthContext.Provider>
  );
};
